import Navbar from '@componens/navbar/navbar'
import'@styles/global.css'

export const metadata = {
  title: 'Kadek Astri Yani',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  )
}
